namePrefix: dev-
commonLabels:
  variant: dev
bases:
  - ../../base
patchesStrategicMerge:
  - deployment.yaml
configMapGenerator:
  - name: springboot-app-config
    files:
      - application.properties
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: reachnaveen/springboot-app
    newTag: dev-14 # Set dynamically from Jenkins
