namePrefix: qa-
commonLabels:
  variant: qa
bases:
  - ../../base
patchesStrategicMerge:
  - deployment.yaml
configMapGenerator:
  - name: springboot-app-config
    files:
      - application.properties
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: reachnaveen/springboot-app
    newTag: "qa-17" # Set dynamically from Jenkins
