namePrefix: qa-
resources:
  - ../../base
configMapGenerator:
  - files:
      - application.properties
    name: springboot-app-config
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: reachnaveen/springboot-app
    newTag: qa-24
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: qa
patches:
  - path: deployment.yaml
